package com.example.cadenacustodiapp.viewmodel

import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel

class ViewModel: ViewModel() {

    var referenciavm = MutableLiveData<String>()
    var institucionvm = MutableLiveData<String>()
    var foliovm = MutableLiveData<String>()
    var lugarvm = MutableLiveData<String>()
    var fechavm = MutableLiveData<String>()
    var horavm = MutableLiveData<String>()

    var localizacionvm = MutableLiveData<String>()
    var descubrimientovm = MutableLiveData<String>()
    var aportacionvm = MutableLiveData<String>()

    var identificacionvm1= MutableLiveData<String>()
    var descripcionvm1= MutableLiveData<String>()
    var ubicacionvm1= MutableLiveData<String>()
    var recoleccionvm1= MutableLiveData<String>()
    var identificacionvm2= MutableLiveData<String>()
    var descripcionvm2= MutableLiveData<String>()
    var ubicacionvm2= MutableLiveData<String>()
    var recoleccionvm2= MutableLiveData<String>()
    var identificacionvm3= MutableLiveData<String>()
    var descripcionvm3= MutableLiveData<String>()
    var ubicacionvm3= MutableLiveData<String>()
    var recoleccionvm3= MutableLiveData<String>()
    var identificacionvm4= MutableLiveData<String>()
    var descripcionvm4= MutableLiveData<String>()
    var ubicacionvm4= MutableLiveData<String>()
    var recoleccionvm4= MutableLiveData<String>()
    var identificacionvm5= MutableLiveData<String>()
    var descripcionvm5= MutableLiveData<String>()
    var ubicacionvm5= MutableLiveData<String>()
    var recoleccionvm5= MutableLiveData<String>()

    var escritovmSi= MutableLiveData<String>()
    var escritovmNo= MutableLiveData<String>()
    var fotograficovmSi= MutableLiveData<String>()
    var fotograficovmNo= MutableLiveData<String>()
    var croquisvmSi= MutableLiveData<String>()
    var croquisvmNo= MutableLiveData<String>()
    var otrovmSi= MutableLiveData<String>()
    var otrovmNo= MutableLiveData<String>()
    var especifiquevm= MutableLiveData<String>()

    var rmanualvm= MutableLiveData<String>()
    var rinstrumentalvm= MutableLiveData<String>()

    var bolsavm= MutableLiveData<String>()
    var cajavm= MutableLiveData<String>()
    var recipientevm= MutableLiveData<String>()

    var servpubvm1= MutableLiveData<String>()
    var instvm1= MutableLiveData<String>()
    var crgvm1= MutableLiveData<String>()
    var etpvm1= MutableLiveData<String>()
    var servpubvm2= MutableLiveData<String>()
    var instvm2= MutableLiveData<String>()
    var crgvm2= MutableLiveData<String>()
    var etpvm2= MutableLiveData<String>()
    var servpubvm3= MutableLiveData<String>()
    var instvm3= MutableLiveData<String>()
    var crgvm3= MutableLiveData<String>()
    var etpvm3= MutableLiveData<String>()
    var servpubvm4= MutableLiveData<String>()
    var instvm4= MutableLiveData<String>()
    var crgvm4= MutableLiveData<String>()
    var etpvm4= MutableLiveData<String>()
    var servpubvm5= MutableLiveData<String>()
    var instvm5= MutableLiveData<String>()
    var crgvm5= MutableLiveData<String>()
    var etpvm5= MutableLiveData<String>()
    var servpubvm6= MutableLiveData<String>()
    var instvm6= MutableLiveData<String>()
    var crgvm6= MutableLiveData<String>()
    var etpvm6= MutableLiveData<String>()
    var servpubvm7= MutableLiveData<String>()
    var instvm7= MutableLiveData<String>()
    var crgvm7= MutableLiveData<String>()
    var etpvm7= MutableLiveData<String>()

    var terrestrevm= MutableLiveData<String>()
    var aereavm= MutableLiveData<String>()
    var maritimavm= MutableLiveData<String>()
    var condSivm= MutableLiveData<String>()
    var condNovm= MutableLiveData<String>()
    var recomendacionvm= MutableLiveData<String>()
}